[project]
name = "abodephysicshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "huggingface>=0.0.1",
    "outlines>=1.2.5",
    "pydantic>=2.11.9",
    "transformers>=4.56.2",
]
